### PR TITLE
syschdemd: add deprecation notice

### PR DESCRIPTION
**Pull request by nzbr**
This should ideally be merged after #466

### CODE REVIEW

**Review by K900 — APPROVED** [review]
LGTM. Should we have a deadline? 24.11?

**Comment by nzbr** [comment]
I also removed the legacy tarball from the CI pipeline now.
24.11 makes sense - it will be deprecated with 24.05 and removed one release later

**Comment by K900** [comment]
Should probably add that to the message then.

**Comment by nzbr** [comment]
Will do (after i fix the pipeline, whoops)

**Pull request merged**
