### PR TITLE
docs: add certificate install instructions

### PR DESCRIPTION
**Pull request by Rasmus-Bertell**
Adds instructions to install the certificate if using the `.msixbundle` launcher.

### CODE REVIEW

**Review by SuperSandro2000 — APPROVED** [review]

**Review by malik-n — CHANGES_REQUESTED** [review]
is this really part of the scope of the install page?
It makes it look like Mixbundle would be part of the default path of installing NixOS-WSL even though I am still not quiet sure what Mixbundle is.

**Comment by Rasmus-Bertell** [comment]
> is this really part of the scope of the install page? It makes it look like Mixbundle would be part of the default path of installing NixOS-WSL even though I am still not quiet sure what Mixbundle is.

I think it's pretty crucial since the `.msixbundle` launcher can't be used, at least on some systems, without the certificate. I only knew how to install the certificate because I had done it previously for   [ArchWSL](https://github.com/yuk7/ArchWSL)[^1]. Another option in my opinion would be to link the ArchWSL docs on how to do it.

[^1]: https://wsldl-pg.github.io/ArchW-docs/Install-Certificate/

**Comment by malik-n** [comment]
> > is this really part of the scope of the install page? It makes it look like Mixbundle would be part of the default path of installing NixOS-WSL even though I am still not quiet sure what Mixbundle is.
> 
> I think it's pretty crucial since the `.msixbundle` launcher can't be used, at least on some systems, without the certificate. I only knew how to install the certificate because I had done it previously for [ArchWSL](https://github.com/yuk7/ArchWSL)[1](#user-content-fn-1-75e8d91385e4e0f96bb27354a756bfdf). Another option in my opinion would be to link the ArchWSL docs on how to do it.
> 
> ## Footnotes
> 1. https://wsldl-pg.github.io/ArchW-docs/Install-Certificate/ [↩](#user-content-fnref-1-75e8d91385e4e0f96bb27354a756bfdf)

Knowing how to setup msixbundle might be crucial if you are a user of that software. There is lots of software that might be crucial to some users.
I suggest to move that setup guide to [/docs/src/how-to](https://github.com/nix-community/NixOS-WSL/tree/main/docs/src/how-to)

**Comment by Rasmus-Bertell** [comment]
Moved it into how-to section. Let me know if other changes are needed.

**Comment by malik-n** [comment]
> Moved it into how-to section. Let me know if other changes are needed.

its not up to me 
but I would aproove when you change the file name to something more specific

**Comment by nzbr** [comment]
I think it's fine to keep it in the how-to section for now, as the default install method for most people will still be the tarball without the launcher

**Pull request merged**
