### PR TITLE
Add option to disable error about ldconfig

### PR DESCRIPTION
**Pull request by SuperSandro2000**

### CODE REVIEW

**Comment by nzbr** [comment]
Is this option documented somewhere by Microsoft? I tried to look it up but couldn't find anything

**Comment by SuperSandro2000** [comment]
The option was written into the error message in dmesg.

**Comment by nzbr** [comment]
Given that you wrote that it doesn't work with NixOS: Should we add a warning if someone tries to use it anyway?

**Comment by SuperSandro2000** [comment]
I mean, if people provide the directories and /sbin/ldconfig then it might work, not sure. I don't think we need to add a warning for this now.

**Pull request merged**
